BEGIN;

DROP TABLE human CASCADE;
DROP TABLE planet CASCADE;
DROP TABLE robot CASCADE;
DROP TABLE human_group CASCADE;
DROP TABLE galaxy;
DROP TABLE eyes CASCADE;
DROP TABLE robots_of_group CASCADE;


DROP TYPE translation_status CASCADE;

COMMIT;