name: Lab automatic build

on:
  push:
    branches:
      - 'lab4-impl'

jobs:
  build_jar:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'openjdk'
      - name: Build runnable jar file
        run: |
          mkdir build/comp
          shopt -s globstar
          javac -d build/comp src/com/mitrian/lab/Main.java src/com/mitrian/lab/**/*.java
          jar -cfm ./build/lab4-release.jar ./build/MANIFEST.MF -C ./build/comp .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lab4-release.jar
          path: build/lab4-release.jar
      - name: Create release
        id: create_draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Lab4 release ${{ github.run_number }}
          body: Lab4 implementation
          draft: true
          prerelease: false
      - name: Upload release assets
        id: upload_releases_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
          asset_path: ./build/lab4-release.jar
          asset_name: lab4-release-v${{ github.run_number }}.jar
          asset_content_type: application/zip